[theme]
primaryColor = "#1E1E1E"  # Example dark color
backgroundColor = "#0E1117"  # Dark background color
secondaryBackgroundColor = "#1E1E1E"  # Dark secondary background color
textColor = "#FFFFFF"  # White text color